image: python:3.10

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - python manage.py test
    - step:
        name: Build Docker Image
        script:
          - docker build -t my-django-app .
    - step:
        name: Deploy to Production
        deployment: production
        script:
          - pipe: atlassian/docker-push:1.3.0
            variables:
              IMAGE_NAME: 'your-docker-registry/my-django-app'
              TAG: 'latest'
          - ssh root@89.111.170.246 "docker pull your-docker-registry/my-django-app:latest && docker-compose up -d"