services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14.12
    ports:
      - 5432:5432
    container_name: pgdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=vitaliy
      - POSTGRES_PASSWORD=1235
      - POSTGRES_DB=docker_project

volumes:
      postgres_data: