image: docker:latest

services:
  - docker:dined

variables:
  DOCKER_DRIVER: overlay2
  PROJECT_NAME: my-django-app
  REGISTRY: registry.gitlab.com
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

stages:
  - build
  - test
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - main

test:
  stage: test
  script:
    - docker run --rm $IMAGE_TAG python manage.py test
  only:
    - merge_requests

deploy:
  stage: deploy
  script:
    - echo "Deploying to production server..."
    - ssh root@89.111.170.246 "docker pull $IMAGE_TAG && docker-compose up -d"
  only:
    - tags